all:
  hosts:
    edgepaas-ec2:
      ansible_host: 44.213.113.60
      ansible_user: ec2-user
      ansible_private_key_file: /home/codest/Main/proj/devops/edgepaas/ansible/files/tf-web-key.pem
      ansible_python_interpreter: /usr/bin/python3
