all:
  hosts:
    edgepaas_ec2:
      ansible_host: "98.92.203.48"
      ansible_user: "ec2-user"
      ansible_private_key_file: "/home/codest/Main/devops/edgepaas/ansible/roles/app/files/tf-web-key.pem"
      ansible_python_interpreter: "/usr/bin/python3"
      ansible_ssh_args: ' -o StrictHostKeyChecking=no'
