all:
  hosts:
    edgepaas-ec2:
      ansible_host: 34.234.172.78
      ansible_user: ec2-user
      ansible_private_key_file: /home/codest/Main/proj/devops/edgepaas/ansible/roles/app/files/tf-web-key.pem
      ansible_python_interpreter: /usr/bin/python3
