#version: '3.9'
# Local Docker compose

services:
  # --- FastAPI App ---
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.dev
    environment:
      DOCKER: "true"
      DEV_DB_USER: "weather"
      DEV_DB_PASSWORD: "weather123"
      DEV_DB_NAME: "weather_app_db"
      DEV_DB_HOST: "db"

    networks:
      - app_net

  # --- Postgres DB ---
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather123
      POSTGRES_DB: weather_app_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U weather -d weather_app_db"]
      interval: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net


# --- Networks ---
networks:
  app_net:
    driver: bridge

# --- Volumes ---
volumes:
  db_data:
    driver: local
