---
# Default variables for EdgePaaS app role

# Docker Hub user (from GitHub Actions secret or default)
dockerhub_user: "{{ lookup('env','DOCKER_USER') | default('codest40', true) }}"

# Application name
app_name: edgeapp

# Container port inside the container
container_port: 80

# Blue-green deployment colors
active_color: "{{ lookup('env','ACTIVE_COLOR') | default('blue', true) }}"
inactive_color: "{{ lookup('env','INACTIVE_COLOR') | default('green', true) }}"

# Ports on host
active_port: 8081
inactive_port: 8080
