---
# Default variables for EdgePaaS app role

# Docker Hub user (from GitHub Actions secret or default)
dockerhub_user: "{{ lookup('env','DOCKER_USER') | default('codest40', true) }}"

# Application name
app_name: edgeapp

# Container port inside the container
container_port: 80

# Ports on host
supplied_active_port: 8080
supplied_inactive_port: 8081
