name: Test Health Check Again (Test-Ansible)

on:
  push: {}
  workflow_dispatch:

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  APP_NAME: edgeapp
  EC2_IP: ${{ secrets.EC2_IP }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Extract Clean IP For Use
        run: |
          IP="${{ secrets.EC2_IP }}"

          IFS='.' read -r IP1 IP2 IP3 IP4 <<< "$IP"

          echo "EC2_IP_1=$IP1" >> $GITHUB_ENV
          echo "EC2_IP_2=$IP2" >> $GITHUB_ENV
          echo "EC2_IP_3=$IP3" >> $GITHUB_ENV
          echo "EC2_IP_4=$IP4" >> $GITHUB_ENV

          echo "EC2 IP split into parts"

          # Debug
          echo "Fourth: EC2_IP_4"
          echo "Third: EC2_IP_3"

      - name: Rebuild And Pass Along
        run: |
          EC2_IP="${EC2_IP_1}.${EC2_IP_2}.${EC2_IP_3}.${EC2_IP_4}"
          echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV

          echo "EC2 IP rebuilt successfully"

      - name: Setup SSH key
        run : |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add dynamic EC2 IP to known_hosts safely
          ssh-keyscan -H "$EC2_IP" >> ~/.ssh/known_hosts 2>/dev/null

      - name: Run All playbooks
        working-directory: test_dir
        run: |
          ansible-playbook \
            -i inventory.ini \
            run.yml \
             --extra-vars "DOCKER_USER=${DOCKER_USER} APP_NAME=${APP_NAME} EC2_IP=${EC2_IP}"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          RUN_MIGRATIONS: ${{ secrets.RUN_MIGRATIONS }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          APP_NAME: edgeapp
