name: TEST Create TERRAFORM

on:
  push: {}
  dispatch_workflows:
    inputs:
      tf_action:
        description: 'Destroy TF Infra'
        required: false
        default: destroy

permisssions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.6.6
  TF_IN_AUTOMATION: true
  TF_DIR: ./iac
  TF_VAR_key: ${{ secrets.KEY }}
  TF_VAR_my_ip_cidr: ${{ secrets.MY_IP_CIDR }}
  TF_VAR_alert_emails: ${{ secrets.ALERT_EMAILS }}
  TF_VAR_amount: ${{ secrets.BUDGET_AMOUNT }}
  EDGEPAAS_AWS_ROLE: ${{ secrets.EDGEPAAS_AWS_ROLE }}

jobs:
  iac_provision:
    runs-on: ubuntu-latest

    steps:
      - name: checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.EDGEPAAS_AWS_ROLE }}
          aws-region: us-east-1

     - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

     - name: Terraform Init
       run: |
         echo "Starting Terraform Provision.."
         terraform init -input=false -reconfigure
       working-directory: ${{ env.TF_DIR }}

     - name: Terraform Format
       run: |
         terraform fmt -recursive
       working-directory: ${{ env.TF_DIR }}

     - name: Terraform validate
       run: |
         terraform validate
       working-directory: ${{ env.TF_DIR }}

     - name: Terraform plan
       run: |
         terraform plan -var "alert_emails=$EMAIL_TO amount=$TF_AMOUNT cidr_blocks=$my_ip_cidr" -input=false -lock-timeout=3m
       working-directory: ${{ env.TF_DIR }}

     - name: Terraform Apply
       run: |
         terraform apply -var "alert_emails=$EMAIL_TO amount=$TF_AMOUNT cidr_blocks=$my_ip_cidr" -input=false -lock-timeout=3m
       working-directory: ${{ env.TF_DIR }}

      - name: Terraform Destroy
        if: ${{ github.event.inputs.tf_action == 'destroy' }}
        run: terraform destroy -auto-approve -input=false -var "alert_emails=$EMAIL_TO amount=$TF_AMOUNT cidr_blocks=$my_ip_cidr -input=false -lock-timeout=3m"
        working-directory: ${{ env.TF_DIR }}

