name: TEST Create TERRAFORM

on:
  push: {}

env:

jobs:
  iac_provision:
    runs-on: ubuntu-latest

    steps:
      - name: checkout Code
        uses: actions/checkout@v4

     - name: Test It
       run: |
         echo "Testing Only"
